# Generated by Django 5.2.8 on 2025-11-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato'), ('Outro', 'Outro'), ('Indefinido', 'Idenfinido')], default='Indefinido', max_length=255)),
                ('cor', models.CharField(max_length=255)),
            ],
        ),
    ]
